<?php

namespace NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsRepository extends EntityRepository
{
}
